name: flutter_map_location
description: flutter_map plugin to request and display the users location and heading on the map.
version: 1.0.0
publish_to: none
homepage: https://github.com/sergey-s-moiseev/user_location_plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass:
    git:
      url: git@github.com:sergey-s-moiseev/flutter_compass.git
  flutter_map: ^0.14.0
  geolocator: ^8.0.3
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
